// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu6psnDE52oRqmM9PMi2xczwsJybPJ45M',
    appId: '1:404585085347:web:3a783d0d700669649f8216',
    messagingSenderId: '404585085347',
    projectId: 'mcauthapp-34bb6',
    authDomain: 'mcauthapp-34bb6.firebaseapp.com',
    storageBucket: 'mcauthapp-34bb6.appspot.com',
    measurementId: 'G-364M7E5E5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG8KqXUfzOdMIYZi34r1lnBFaiVh5rzOg',
    appId: '1:404585085347:android:dd098017317603699f8216',
    messagingSenderId: '404585085347',
    projectId: 'mcauthapp-34bb6',
    storageBucket: 'mcauthapp-34bb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-aWSe3PN8b3oNwVe2feZQSst2P_Ba2Uo',
    appId: '1:404585085347:ios:785ed765a3a97a9b9f8216',
    messagingSenderId: '404585085347',
    projectId: 'mcauthapp-34bb6',
    storageBucket: 'mcauthapp-34bb6.appspot.com',
    iosBundleId: 'com.example.madinati',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-aWSe3PN8b3oNwVe2feZQSst2P_Ba2Uo',
    appId: '1:404585085347:ios:785ed765a3a97a9b9f8216',
    messagingSenderId: '404585085347',
    projectId: 'mcauthapp-34bb6',
    storageBucket: 'mcauthapp-34bb6.appspot.com',
    iosBundleId: 'com.example.madinati',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu6psnDE52oRqmM9PMi2xczwsJybPJ45M',
    appId: '1:404585085347:web:380eef26b8ed66909f8216',
    messagingSenderId: '404585085347',
    projectId: 'mcauthapp-34bb6',
    authDomain: 'mcauthapp-34bb6.firebaseapp.com',
    storageBucket: 'mcauthapp-34bb6.appspot.com',
    measurementId: 'G-ZFEQYZQ8PP',
  );
}
